//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStore.AdminEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarouselSlider
    {
        public int Id { get; set; }
        public string IName { get; set; }
        public string FilePath { get; set; }
        public byte[] Image { get; set; }
        public string MobileImageFilePath { get; set; }
        public byte[] MobileImage { get; set; }
    }
}
