//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStore.AdminEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerContent
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string IpAddress { get; set; }
        public bool IsApproved { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public System.DateTime UpdatedOnUtc { get; set; }
    
        public virtual BlogComment BlogComment { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ForumPostVote ForumPostVote { get; set; }
        public virtual NewsComment NewsComment { get; set; }
        public virtual ProductReview ProductReview { get; set; }
        public virtual ProductReviewHelpfulness ProductReviewHelpfulness { get; set; }
        public virtual PollAnswer PollAnswer { get; set; }
    }
}
