//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStore.AdminEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryTime()
        {
            this.Products = new HashSet<Product>();
            this.ProductVariantAttributeCombinations = new HashSet<ProductVariantAttributeCombination>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ColorHexValue { get; set; }
        public string DisplayLocale { get; set; }
        public int DisplayOrder { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> MinDays { get; set; }
        public Nullable<int> MaxDays { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVariantAttributeCombination> ProductVariantAttributeCombinations { get; set; }
    }
}
