//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStore.AdminEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Download
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Download()
        {
            this.Products = new HashSet<Product>();
            this.QueuedEmailAttachments = new HashSet<QueuedEmailAttachment>();
        }
    
        public int Id { get; set; }
        public System.Guid DownloadGuid { get; set; }
        public bool UseDownloadUrl { get; set; }
        public string DownloadUrl { get; set; }
        public string ContentType { get; set; }
        public string Filename { get; set; }
        public string Extension { get; set; }
        public bool IsTransient { get; set; }
        public System.DateTime UpdatedOnUtc { get; set; }
        public Nullable<int> MediaStorageId { get; set; }
        public int EntityId { get; set; }
        public string EntityName { get; set; }
        public string FileVersion { get; set; }
        public string Changelog { get; set; }
        public Nullable<int> MediaFileId { get; set; }
    
        public virtual MediaFile MediaFile { get; set; }
        public virtual MediaStorage MediaStorage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueuedEmailAttachment> QueuedEmailAttachments { get; set; }
    }
}
