//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStore.AdminEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExportProfile()
        {
            this.ExportDeployments = new HashSet<ExportDeployment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string FolderName { get; set; }
        public string FileNamePattern { get; set; }
        public string SystemName { get; set; }
        public string ProviderSystemName { get; set; }
        public bool IsSystemProfile { get; set; }
        public bool Enabled { get; set; }
        public int SchedulingTaskId { get; set; }
        public string Filtering { get; set; }
        public string Projection { get; set; }
        public string ProviderConfigData { get; set; }
        public string ResultInfo { get; set; }
        public int Offset { get; set; }
        public int Limit { get; set; }
        public int BatchSize { get; set; }
        public bool PerStore { get; set; }
        public int EmailAccountId { get; set; }
        public string CompletedEmailAddresses { get; set; }
        public bool CreateZipArchive { get; set; }
        public bool Cleanup { get; set; }
        public bool ExportRelatedData { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExportDeployment> ExportDeployments { get; set; }
        public virtual ScheduleTask ScheduleTask { get; set; }
    }
}
