//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStore.AdminEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportDeployment
    {
        public int Id { get; set; }
        public int ProfileId { get; set; }
        public string Name { get; set; }
        public bool Enabled { get; set; }
        public string ResultInfo { get; set; }
        public int DeploymentTypeId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Url { get; set; }
        public int HttpTransmissionTypeId { get; set; }
        public int HttpTransmissionType { get; set; }
        public string FileSystemPath { get; set; }
        public string SubFolder { get; set; }
        public string EmailAddresses { get; set; }
        public string EmailSubject { get; set; }
        public int EmailAccountId { get; set; }
        public bool PassiveMode { get; set; }
        public bool UseSsl { get; set; }
    
        public virtual ExportProfile ExportProfile { get; set; }
    }
}
