//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStore.AdminEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MediaFile()
        {
            this.BlogPosts = new HashSet<BlogPost>();
            this.BlogPosts1 = new HashSet<BlogPost>();
            this.Categories = new HashSet<Category>();
            this.CheckoutAttributeValues = new HashSet<CheckoutAttributeValue>();
            this.Downloads = new HashSet<Download>();
            this.Manufacturers = new HashSet<Manufacturer>();
            this.MediaTracks = new HashSet<MediaTrack>();
            this.News = new HashSet<News>();
            this.News1 = new HashSet<News>();
            this.Product_MediaFile_Mapping = new HashSet<Product_MediaFile_Mapping>();
            this.QueuedEmailAttachments = new HashSet<QueuedEmailAttachment>();
            this.MediaTags = new HashSet<MediaTag>();
        }
    
        public int Id { get; set; }
        public string MimeType { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public string Name { get; set; }
        public bool IsTransient { get; set; }
        public System.DateTime UpdatedOnUtc { get; set; }
        public Nullable<int> MediaStorageId { get; set; }
        public Nullable<int> FolderId { get; set; }
        public string Alt { get; set; }
        public string Title { get; set; }
        public string Extension { get; set; }
        public string MediaType { get; set; }
        public int Size { get; set; }
        public Nullable<int> PixelSize { get; set; }
        public string Metadata { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public bool Deleted { get; set; }
        public bool Hidden { get; set; }
        public int Version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogPost> BlogPosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogPost> BlogPosts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckoutAttributeValue> CheckoutAttributeValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Download> Downloads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manufacturer> Manufacturers { get; set; }
        public virtual MediaFolder MediaFolder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MediaTrack> MediaTracks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News> News { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News> News1 { get; set; }
        public virtual MediaStorage MediaStorage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_MediaFile_Mapping> Product_MediaFile_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueuedEmailAttachment> QueuedEmailAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MediaTag> MediaTags { get; set; }
    }
}
