//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStore.AdminEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItemRecord
    {
        public int Id { get; set; }
        public int MenuId { get; set; }
        public int ParentItemId { get; set; }
        public string ProviderName { get; set; }
        public string Model { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string PermissionNames { get; set; }
        public bool Published { get; set; }
        public int DisplayOrder { get; set; }
        public bool BeginGroup { get; set; }
        public bool ShowExpanded { get; set; }
        public bool NoFollow { get; set; }
        public bool NewWindow { get; set; }
        public string Icon { get; set; }
        public string Style { get; set; }
        public string HtmlId { get; set; }
        public string CssClass { get; set; }
        public string IconColor { get; set; }
        public bool LimitedToStores { get; set; }
        public bool SubjectToAcl { get; set; }
    
        public virtual MenuRecord MenuRecord { get; set; }
    }
}
