//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStore.AdminEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariantAttributeCombination
    {
        public int Id { get; set; }
        public string Sku { get; set; }
        public string Gtin { get; set; }
        public string ManufacturerPartNumber { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> BasePriceAmount { get; set; }
        public Nullable<int> BasePriceBaseAmount { get; set; }
        public string AssignedMediaFileIds { get; set; }
        public Nullable<int> DeliveryTimeId { get; set; }
        public Nullable<int> QuantityUnitId { get; set; }
        public bool IsActive { get; set; }
        public int ProductId { get; set; }
        public string AttributesXml { get; set; }
        public int StockQuantity { get; set; }
        public bool AllowOutOfStockOrders { get; set; }
    
        public virtual DeliveryTime DeliveryTime { get; set; }
        public virtual Product Product { get; set; }
        public virtual QuantityUnit QuantityUnit { get; set; }
    }
}
