//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStore.AdminEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariantAttributeValue
    {
        public int Id { get; set; }
        public int ProductVariantAttributeId { get; set; }
        public string Alias { get; set; }
        public string Name { get; set; }
        public int MediaFileId { get; set; }
        public string Color { get; set; }
        public decimal PriceAdjustment { get; set; }
        public decimal WeightAdjustment { get; set; }
        public bool IsPreSelected { get; set; }
        public int DisplayOrder { get; set; }
        public int ValueTypeId { get; set; }
        public int LinkedProductId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Product_ProductAttribute_Mapping Product_ProductAttribute_Mapping { get; set; }
    }
}
