//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStore.AdminEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductBundleItemAttributeFilter
    {
        public int Id { get; set; }
        public int BundleItemId { get; set; }
        public int AttributeId { get; set; }
        public int AttributeValueId { get; set; }
        public bool IsPreSelected { get; set; }
    
        public virtual ProductBundleItem ProductBundleItem { get; set; }
    }
}
