//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStore.AdminEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductBundleItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductBundleItem()
        {
            this.ProductBundleItemAttributeFilters = new HashSet<ProductBundleItemAttributeFilter>();
            this.ShoppingCartItems = new HashSet<ShoppingCartItem>();
        }
    
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int BundleProductId { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public bool DiscountPercentage { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public bool FilterAttributes { get; set; }
        public bool HideThumbnail { get; set; }
        public bool Visible { get; set; }
        public bool Published { get; set; }
        public int DisplayOrder { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public System.DateTime UpdatedOnUtc { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Product Product1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductBundleItemAttributeFilter> ProductBundleItemAttributeFilters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCartItem> ShoppingCartItems { get; set; }
    }
}
