//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStore.AdminEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueuedEmailAttachment
    {
        public int Id { get; set; }
        public int QueuedEmailId { get; set; }
        public int StorageLocation { get; set; }
        public string Path { get; set; }
        public Nullable<int> FileId { get; set; }
        public byte[] Data { get; set; }
        public string Name { get; set; }
        public string MimeType { get; set; }
        public Nullable<int> MediaStorageId { get; set; }
        public Nullable<int> MediaFileId { get; set; }
    
        public virtual Download Download { get; set; }
        public virtual MediaFile MediaFile { get; set; }
        public virtual MediaStorage MediaStorage { get; set; }
        public virtual QueuedEmail QueuedEmail { get; set; }
    }
}
