//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStore.AdminEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueuedEmail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QueuedEmail()
        {
            this.QueuedEmailAttachments = new HashSet<QueuedEmailAttachment>();
        }
    
        public int Id { get; set; }
        public int Priority { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string ReplyTo { get; set; }
        public string CC { get; set; }
        public string Bcc { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public int SentTries { get; set; }
        public Nullable<System.DateTime> SentOnUtc { get; set; }
        public int EmailAccountId { get; set; }
        public bool SendManually { get; set; }
    
        public virtual EmailAccount EmailAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueuedEmailAttachment> QueuedEmailAttachments { get; set; }
    }
}
