//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStore.AdminEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleTaskHistory
    {
        public int Id { get; set; }
        public int ScheduleTaskId { get; set; }
        public bool IsRunning { get; set; }
        public string MachineName { get; set; }
        public System.DateTime StartedOnUtc { get; set; }
        public Nullable<System.DateTime> FinishedOnUtc { get; set; }
        public Nullable<System.DateTime> SucceededOnUtc { get; set; }
        public string Error { get; set; }
        public Nullable<int> ProgressPercent { get; set; }
        public string ProgressMessage { get; set; }
    
        public virtual ScheduleTask ScheduleTask { get; set; }
    }
}
