//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStore.AdminEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncMapping
    {
        public int Id { get; set; }
        public int EntityId { get; set; }
        public string SourceKey { get; set; }
        public string EntityName { get; set; }
        public string ContextName { get; set; }
        public string SourceHash { get; set; }
        public Nullable<int> CustomInt { get; set; }
        public string CustomString { get; set; }
        public Nullable<bool> CustomBool { get; set; }
        public System.DateTime SyncedOnUtc { get; set; }
    }
}
