//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStore.AdminEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public int Id { get; set; }
        public string SystemName { get; set; }
        public bool IncludeInSitemap { get; set; }
        public bool IsPasswordProtected { get; set; }
        public string Password { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public string MetaTitle { get; set; }
        public bool LimitedToStores { get; set; }
        public bool RenderAsWidget { get; set; }
        public string WidgetZone { get; set; }
        public Nullable<bool> WidgetWrapContent { get; set; }
        public bool WidgetShowTitle { get; set; }
        public bool WidgetBordered { get; set; }
        public int Priority { get; set; }
        public string TitleTag { get; set; }
        public bool IsSystemTopic { get; set; }
        public string ShortTitle { get; set; }
        public string Intro { get; set; }
        public bool SubjectToAcl { get; set; }
        public bool IsPublished { get; set; }
        public string HtmlId { get; set; }
        public string BodyCssClass { get; set; }
        public Nullable<int> CookieType { get; set; }
    }
}
