//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStore.AdminEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletHistory
    {
        public int Id { get; set; }
        public int StoreId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public decimal Amount { get; set; }
        public decimal AmountBalance { get; set; }
        public decimal AmountBalancePerStore { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public Nullable<int> Reason { get; set; }
        public string Message { get; set; }
        public string AdminComment { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Order Order { get; set; }
    }
}
